### ISSUE TITLE
noob questions

### ISSUE THREAD

**Issue by aafuni** [lilhoser/pizzawave#11]
I am new to Trunk Recorder, and think I have that half of the equation set up right but is there a way to verify?  Is there something I am missing to see the stream in pizzaui, all the readmes seem to only talk about prerecorded streams? Do you have a screen shot of what things look like on the server side when it is correctly configured and running?

I am running trunk recorder on a pi and see it load the callstream plug in.  I have pizzaui on a windows machine with the callstream IP pointing to the windows machines IP.

**Comment by lilhoser** [comment]
Hey there, thanks for trying out the tool.

Live captures are described [here](https://github.com/lilhoser/pizzawave#Running). To start one in `pizzaui`, navigate to `File` -> `Call Manager` -> `Start`

<img width="300" alt="image" src="https://github.com/user-attachments/assets/2ade4cae-1c7b-4323-a9b4-95136e8e087f">

If you have your trunk recorder server configured correctly, you should begin receiving live call data (see "receiving from" in lower right corner of the window's status bar):

<img width="935" alt="image" src="https://github.com/user-attachments/assets/f497aaa6-86ec-401d-bb46-452446298a8d">

Server side is pretty simple, but your configuration has to be correct (and of course, your client and server need to be able to communicate over your network). The [`callstream` plugin page](https://github.com/lilhoser/callstream) describes the configuration in pretty good detail, but let me know if you have specific questions. You should check the console output on the server from your execution of trunk recorder (eg, `./trunk-recorder --config=config.json`) - look for `callstream` messages that indicate whether or not it has an active client available.

**Comment by aafuni** [comment]
Ah, issue is on the Pizza side.  I didn't see the error at the bottom: "Unable to initialize live call manager: Unable to initialize call manager: Failed to build processor/factory: Failed to load native whisper library. Error: The Specified module could not be found."

**Comment by lilhoser** [comment]
Sounds like you don't have whisper installed correctly.  Follow the section `Using Whisper for Transcription` [here](https://github.com/lilhoser/pizzawave/tree/main/pizzalib)

**Comment by lilhoser** [comment]
If you don't know how to clone/build the repo, let me know - I can build you a package real quick that should work.

**Comment by aafuni** [comment]
That would be awesome, this is my first time working with .net packages.

**Comment by lilhoser** [comment]
Try this release: https://github.com/lilhoser/pizzawave/releases/tag/1.0.2-pizzaui-cpu-only

**Comment by aafuni** [comment]
Thank you so much, that did it.  System is working great now.
